### ISSUE TITLE
Reuse existing ZSH prompt?

### ISSUE THREAD

**Issue by aronchick** [omkensey/demo-magic-redux#1]
Hi! I love what you've done here - I have a pretty finely crafted ZSH prompt - is there any way to reuse it?

**Comment by omkensey** [comment]
`DEMO_PROMPT` should allow you to set the script prompt to whatever you want; I vaguely recall that I tried just setting `DEMO_PROMPT=$PS1` and that doesn't "pass through" the prompt parameters but sets the prompt to the rendered prompt at the time the script runs, and that there's a workaround (but I forget what it is -- I'm also not familiar with zsh specifics so it's possible the workaround works in bash but not zsh).

I'm making some changes to how things are passed in from the environment so I'll noodle around with it.

**Comment by aronchick** [comment]
Thanks! Yeah, i guess i'm just looking to replicate my local (very complicated) PS1 - from p10k. But that may not be necessary.

**Comment by omkensey** [comment]
I think with the change I just merged in, this is (relatively) straightforward.  It comes down to doing one of the following:

* export your PS1 in your *rc files so that subshells inherit it, then add a line in your script to set `DEMO_MAGIC_PROMPT="$PS1"` before sourcing demo-magic.sh.
* pass it in externally when you call a demo-magic'ed script, a la: `DEMO_PROMPT="$PS1" bash ./demo-magic-test.sh` (in your case I think you'd use zsh

Either of those should work; I tested the second successfully but didn't want to monkey around too deeply with my own rc files testing the first one :)
